#server:
#  port: 8080
#  servlet:
#    context-path: /api
#
#spring:
#  application:
#    name: week03
#
#app:
#  app-name: 企业后台管理系统
#  version: 1.0.0
#  description: 基于SpringBoot3.5.1构成
#  published: false
#  author:
#    name: zhangxin
#    webiste: https://zhangxin
#    email: 3389747021@qq.com
spring:
  profiles:
    active: test