spring:

  # Redis ??
  data:
    redis:
      # Redis ?????
      host: localhost
      # Redis ?????
      port: 6379
      # ?????????????
      # password: abc123
      # ??????????
      timeout: 5000ms
      # ????? 0-15
      database: 0
      # ?? Lettuce?
      lettuce:
        pool:
          # ?????
          max-active: 200
          # ??????????
          max-wait: -1ms
          # ???????
          max-idle: 10
          # ???????
          min-idle: 0
          # ????????
